name: Build TeX

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Cache TeXLive
      uses: actions/cache@v3
      id: texlive
      with:
        path: /usr/local/texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('texlive.profile') }}

    - name: Install TeX Live
      if: steps.texlive.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full

    - name: Clean
      run: make clean

    - name: Build TeX
      run: make || exit 1

    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Automatic PDF generation"
        head: develop
        base: main